landmarks_names = [
    "wrist",
    "thumb_cmc",
    "thumb_mcp",
    "thumb_ip",
    "thumb_tip",
    "index_finger_mcp",
    "index_finger_pip",
    "index_finger_dip",
    "index_finger_tip",
    "middle_finger_mcp",
    "middle_finger_pip",
    "middle_finger_dip",
    "middle_finger_tip",
    "ring_finger_mcp",
    "ring_finger_pip",
    "ring_finger_dip",
    "ring_finger_tip",
    "pinky_mcp",
    "pinky_pip",
    "pinky_dip",
    "pinky_tip",
]

bone_lmk_correspondence = {
    "thumb.01": "thumb_cmc",
    "thumb.02": "thumb_mcp",
    "thumb.03": "thumb_ip",
    "f_index.01": "index_finger_mcp",
    "f_index.02": "index_finger_pip",
    "f_index.03": "index_finger_dip",
    "f_middle.01": "middle_finger_mcp",
    "f_middle.02": "middle_finger_pip",
    "f_middle.03": "middle_finger_dip",
    "f_ring.01": "ring_finger_mcp",
    "f_ring.02": "ring_finger_pip",
    "f_ring.03": "ring_finger_dip",
    "f_pinky.01": "pinky_mcp",
    "f_pinky.02": "pinky_pip",
    "f_pinky.03": "pinky_dip",
}
